export const CSS_VARS = {
    ACCENT_COLOR: '--rnp-accent-color',
    ACCENT_COLOR_RGB: '--rnp-accent-color-rgb',
    ACCENT_COLOR_DARK: '--rnp-accent-color-dark',
    ACCENT_COLOR_ON_PRIMARY_DARK: '--rnp-accent-color-on-primary-dark',
    ACCENT_COLOR_SHADE_1_DARK: '--rnp-accent-color-shade-1-dark',
    ACCENT_COLOR_SHADE_2_DARK: '--rnp-accent-color-shade-2-dark',
    ACCENT_COLOR_BG_DARK: '--rnp-accent-color-bg-dark',
    
    ACCENT_COLOR_LIGHT: '--rnp-accent-color-light',
    ACCENT_COLOR_ON_PRIMARY_LIGHT: '--rnp-accent-color-on-primary-light',
    ACCENT_COLOR_SHADE_1_LIGHT: '--rnp-accent-color-shade-1-light',
    ACCENT_COLOR_SHADE_2_LIGHT: '--rnp-accent-color-shade-2-light',
    ACCENT_COLOR_BG_LIGHT: '--rnp-accent-color-bg-light',

    LYRIC_ROMAJI_SIZE: '--lyric-romaji-size-em',
    LYRIC_TRANSLATION_SIZE: '--lyric-translation-size-em',
    BG_BLUR: '--bg-blur',
    BG_DIM: '--bg-dim',
    BG_DIM_GRADIENT: '--bg-dim-for-gradient-bg',
    BG_DIM_FLUID: '--bg-dim-for-fluid-bg',
    BG_BLUR_NONE_MASK: '--bg-blur-for-none-bg-mask',
    BG_DIM_NONE_MASK: '--bg-dim-for-none-bg-mask',
    BG_OPACITY: '--bg-opacity',
    FLUID_BLUR: '--fluid-blur',
} as const;

export const CLASSES = {
    BODY_HOVER: 'bottombar-hover',
    CHANGED: 'changed',
    SELECTED: 'selected',
    FULL_SCREEN: 'rnp-full-screen',
    IDLE: 'rnp-idle',
    PLAYING: 'mq-playing',
    PATCHED: 'patched',
    LOADING: 'loading',
    SCROLL: 'scroll',
    HIDDEN_ORIGINAL_LYRIC: 'rnp-hidden-original-lyric',
    REFINED_NOW_PLAYING: 'refined-now-playing',
    NO_MATERIAL_YOU: 'no-material-you-theme',
    GPU_DISABLED: 'gpu-acceleration-disabled',
    SYSTEM_DARK: 'rnp-system-dark',
    SYSTEM_LIGHT: 'rnp-system-light',
} as const;
